version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Dacca
  open-pull-requests-limit: 18
  allow:
  - dependency-type: direct
  - dependency-type: indirect
